#!/usr/bin/env python

import logging
import sys
from os.path import splitext
import networkx as nx


def strip(uri):
    return uri.lstrip('<').rstrip('>')

log = logging.getLogger('rdf2gexf')
logging.basicConfig(level=logging.INFO)

graph = nx.DiGraph()
fname = sys.argv[1]
outname = '%s.gexf' % splitext(fname)[0]

log.info('Reading input from %s' % fname)
fin = open(fname, 'r')
for line in fin:
    s, p, o, _ = [strip(d) for d in line.split(' ')]
    graph.add_edge(s, o, {'label': p})

log.info('Writing gexf to %s' % outname)
nx.write_gexf(graph, outname)
